# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d99b0665550f0042e4f34aaa15853732afc03199748a43b3e955da72898d7ab6fa14ed9f0103a860b2215a7dae2aff39ca217996be052365d32c9fba99f076a5

test:
  secret_key_base: 57c1616550bacd275a5f94254fe2ae98c6ebf3c869561f74523b8048723053f24cbe28d4154836a7d242be278c10e10c4c58d18abc6ca4fb825bd4016bdd5cc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
